--- #YAML:1.0
name:               Search-OpenSearch-Engine-Lucy
version:            0.05
abstract:           Lucy server with OpenSearch results
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:                5.008003
    Search::OpenSearch:  0.15
    SWISH::Prog:         0.54
    SWISH::Prog::Lucy:   0.07
    Test::More:          0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch-Engine-Lucy
    homepage:    https://github.com/karpet/search-opensearch-engine-lucy-perl
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/karpet/search-opensearch-engine-lucy-perl.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
